
version: "3.7"

services:
  writeups-db:
    image: mariadb:latest
    container_name: service-writeups-db
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/writeups/mysql:/var/lib/mysql
    networks:
      - writeups-net
    environment:
      - MYSQL_DATABASE=${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    labels:
      - traefik.enable=false

  writeups:
    image: ghost:latest
    container_name: service-writeups
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/writeups/main:/var/lib/ghost/content
    networks:
      - proxy
      - writeups-net
    links:
      - writeups-db
    depends_on:
      - writeups-db
    environment:
      - url=https://${DOMAIN}
      - database__client=mysql
      - database__connection__host=writeups-db
      - database__connection__database=${DB_DB}
      - database__connection__user=${DB_USER}
      - database__connection__password=${DB_PASS}
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.writeups.tls=true
      - traefik.http.routers.writeups.tls.certresolver=letsencrypt
      - traefik.http.routers.writeups.entrypoints=https
      - traefik.http.routers.writeups.rule=Host(`${DOMAIN}`)
      # Services
      # Removes traefiks ability to see container IP for some reason. Security config somewhere?
      # - traefik.http.services.writeups.loadbalancer.server.port=80
networks:
  writeups-net:
    name: writeups-net
    external: false
  proxy:
    external: true
