
version: "3.7"

services:
  databases-mariadb:
    container_name: service-databases-mariadb
    image: mariadb:latest
    restart: unless-stopped
    command: --innodb-read-only-compressed=OFF
    volumes:
      - ${GLOBAL_STORAGE}/databases/mysql:/var/lib/mysql
    networks:
      - proxy
    environment:
      - MYSQL_DATABASE=${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.database-mariadb.tls=true
      - traefik.http.routers.database-mariadb.tls.certresolver=letsencrypt
      - traefik.http.routers.database-mariadb.entrypoints=https
      - traefik.http.routers.database-mariadb.rule=Host(`${DOMAIN_DB}`)
      # Services
      - traefik.http.services.database-mariadb.loadbalancer.server.port=3306

  databases-redis:
    image: redis:6-alpine
    container_name: service-databases-redis
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/databases/redis:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.databases-redis.tls=true
      - traefik.http.routers.databases-redis.tls.certresolver=letsencrypt
      - traefik.http.routers.databases-redis.entrypoints=https
      - traefik.http.routers.databases-redis.rule=Host(`${DOMAIN_CACHE}`)
      # Services
      - traefik.http.services.databases-redis.loadbalancer.server.port=6379

networks:
  proxy:
    external: true
