
version: "3.7"

services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: service-uptime
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${GLOBAL_STORAGE}/uptime/data:/data
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.uptime.tls=true
      - traefik.http.routers.uptime.tls.certresolver=letsencrypt
      - traefik.http.routers.uptime.entrypoints=https
      - traefik.http.routers.uptime.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.uptime.loadbalancer.server.port=80

networks:
  proxy:
    external: true
