services:
  home-assistant:
    container_name: service-home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${GLOBAL_STORAGE}/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.home-assistant.tls=true
      - traefik.http.routers.home-assistant.tls.certresolver=letsencrypt
      - traefik.http.routers.home-assistant.entrypoints=https
      - traefik.http.routers.home-assistant.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123

networks:
  proxy:
    external: true
