
version: "3.7"

services:
  cloud-db:
    container_name: service-cloud-db
    image: mariadb:latest
    restart: unless-stopped
    command: --innodb-read-only-compressed=OFF
    volumes:
      - ${GLOBAL_STORAGE}/cloud/mysql:/var/lib/mysql
    networks:
      - cloud-net
    environment:
      - MYSQL_DATABASE=${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    labels:
      - traefik.enable=false

  cloud-cache:
    image: redis:6-alpine
    container_name: service-cloud-cache
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/cloud/redis:/data
    networks:
      - cloud-net
    labels:
      - traefik.enable=false

  cloud:
    image: nextcloud:latest
    container_name: service-cloud
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/cloud/html:/var/www/html
    networks:
      - proxy
      - cloud-net
    environment:
      # Required for redirects
      - OVERWRITEHOST=${DOMAIN}
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - APACHE_DISABLE_REWRITE_IP=1
      # Database variables
      - MYSQL_HOST=cloud-db
      - MYSQL_DATABASE=${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - REDIS_HOST=cloud-cache
    links:
      - cloud-db
      - cloud-cache
    depends_on:
      - cloud-db
      - cloud-cache
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.cloud.tls=true
      - traefik.http.routers.cloud.tls.certresolver=letsencrypt
      - traefik.http.routers.cloud.entrypoints=https
      - traefik.http.routers.cloud.rule=Host(`${DOMAIN}`)
      # Middleware
      - traefik.http.middlewares.cloud.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.cloud.headers.framedeny=true
      - traefik.http.middlewares.cloud.headers.sslredirect=true
      - traefik.http.middlewares.cloud.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.cloud.headers.STSPreload=true
      - traefik.http.middlewares.cloud.headers.STSSeconds=315360000
      - traefik.http.middlewares.cloud.headers.forceSTSHeader=true
      - "traefik.http.middlewares.cloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.cloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.cloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      # Router <-> Middleware
      - traefik.http.routers.cloud.middlewares=cloud,cloud-caldav
      # Services
      - traefik.http.services.cloud.loadbalancer.server.port=80

  cloud-cron:
    image: nextcloud:latest
    container_name: service-cloud-cron
    restart: unless-stopped
    entrypoint: /cron.sh
    volumes:
      - ${GLOBAL_STORAGE}/cloud/html:/var/www/html
    networks:
      - cloud-net
    environment:
      - MYSQL_HOST=cloud-db
      - MYSQL_DATABASE=${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - REDIS_HOST=cloud-cache
    depends_on:
      - cloud
    labels:
      - traefik.enable=false

networks:
  cloud-net:
    name: cloud-net
    external: false
  proxy:
    external: true
