
version: "3.7"

services:
  code:
    container_name: service-code
    image: lscr.io/linuxserver/code-server
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=${PASSWORD}
#      - HASHED_PASSWORD=${HASHED_PASSWORD}
#      - SUDO_PASSWORD=${SUDO_PASSWORD}
#      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
    volumes:
      - ${GLOBAL_STORAGE}/code:/config
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.code.tls=true
      - traefik.http.routers.code.tls.certresolver=letsencrypt
      - traefik.http.routers.code.entrypoints=https
      - traefik.http.routers.code.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.code.loadbalancer.server.port=8443

networks:
  proxy:
    external: true
