global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443

providers:
  docker:
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http
pilot:
    token: ""